name: asynconf_2022
description: "\"Correction\" de l'Asynconf 2022"
version: 0.0.1
repository: https://github.com/theskyblockman/asynconf-2022

environment:
  sdk: ^3.2.0-210.3.beta

dependencies:
  args: ^2.4.2
  uuid: ^4.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
